[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["GasContract", "original__GasContract"]

[profile.optimizer_details]
constant_optimizer = true
stack_allocation = true
yul = true
jumpdest_remover = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config